name: main

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: testing component checker
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: components check
        id: components
        uses: ./
        with:
          COMPONENT_FOLDER: '["test_folder/components/**/!(Icons|Illucons)/*!(.story|.test).tsx"]'
          OCCURRENCE_FOLDER: '["test_folder/**/!(Icons|Illucons)/*!(.story|.test).tsx"]'
          COMPONENT_NAME_IGNORE: '["Container"]'
      # Use the output from the `hello` step
      - name: Get the components
        run: echo "components ${{steps.components.outputs.NOT_USED_COMPONENTS}}"
